version: "3"
services:
  secrets:
    image: secrets
    ports:
      - "8080:8080"
    networks:
      - mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=secrets

networks:
  mysql: