version: "3"

services:
  secrets:
    image: secrets
    ports:
      - "8080:8080"
    networks:
      - mysql
    depends_on:
      - mysqldb
    environment:
    - spring.datasource.url=jdbc:mysql://mysqldb:3306/secrets?allowPublicKeyRetrieval=true

    volumes:
    - mysql-volume:/var/lib/mysql

  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306

    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=secrets
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
networks:
  mysql:

volumes:
  mysql-volume: