UPDATE secrets.languages SET messagecontent = 'Abmelden', messagekey = 'welcome.logoff', locale = 'de' WHERE id = 1;
UPDATE secrets.languages SET messagecontent = 'Logoff', messagekey = 'welcome.logoff', locale = 'en' WHERE id = 2;
UPDATE secrets.languages SET messagecontent = 'Profil', messagekey = 'buttons.profile', locale = 'de' WHERE id = 3;
UPDATE secrets.languages SET messagecontent = 'Profile', messagekey = 'buttons.profile', locale = 'en' WHERE id = 4;
UPDATE secrets.languages SET messagecontent = 'Benutzer hinzufügen', messagekey = 'buttons.newuser', locale = 'de' WHERE id = 5;
UPDATE secrets.languages SET messagecontent = 'Add user', messagekey = 'buttons.newuser', locale = 'en' WHERE id = 6;
UPDATE secrets.languages SET messagecontent = 'Benutzerliste', messagekey = 'buttons.userlist', locale = 'de' WHERE id = 7;
UPDATE secrets.languages SET messagecontent = 'Userlist', messagekey = 'buttons.userlist', locale = 'en' WHERE id = 8;
UPDATE secrets.languages SET messagecontent = 'Sprachen', messagekey = 'buttons.lang', locale = 'de' WHERE id = 9;
UPDATE secrets.languages SET messagecontent = 'Languages', messagekey = 'buttons.lang', locale = 'en' WHERE id = 10;
UPDATE secrets.languages SET messagecontent = 'Deutsch', messagekey = 'buttons.lang.german', locale = 'de' WHERE id = 11;
UPDATE secrets.languages SET messagecontent = 'Englisch', messagekey = 'buttons.lang.english', locale = 'de' WHERE id = 12;
UPDATE secrets.languages SET messagecontent = 'German', messagekey = 'buttons.lang.german', locale = 'en' WHERE id = 13;
UPDATE secrets.languages SET messagecontent = 'English', messagekey = 'buttons.lang.english', locale = 'en' WHERE id = 14;
UPDATE secrets.languages SET messagecontent = 'Rollen', messagekey = 'buttons.roles', locale = 'de' WHERE id = 15;
UPDATE secrets.languages SET messagecontent = 'Roles', messagekey = 'buttons.roles', locale = 'en' WHERE id = 16;
UPDATE secrets.languages SET messagecontent = 'Geheimnisse v1.0', messagekey = 'app.title', locale = 'de' WHERE id = 17;
UPDATE secrets.languages SET messagecontent = 'Secrets v1.0', messagekey = 'app.title', locale = 'en' WHERE id = 18;
UPDATE secrets.languages SET messagecontent = 'Rolle', messagekey = 'page.role.name', locale = 'de' WHERE id = 19;
UPDATE secrets.languages SET messagecontent = 'Role', messagekey = 'page.role.name', locale = 'en' WHERE id = 20;
UPDATE secrets.languages SET messagecontent = 'Nr.', messagekey = 'page.role.nr', locale = 'de' WHERE id = 21;
UPDATE secrets.languages SET messagecontent = 'Nr.', messagekey = 'page.role.nr', locale = 'en' WHERE id = 22;
UPDATE secrets.languages SET messagecontent = 'Neue Rolle', messagekey = 'page.role.new', locale = 'de' WHERE id = 23;
UPDATE secrets.languages SET messagecontent = 'New role', messagekey = 'page.role.new', locale = 'en' WHERE id = 24;
UPDATE secrets.languages SET messagecontent = 'Übernehmen', messagekey = 'page.role.submit', locale = 'de' WHERE id = 25;
UPDATE secrets.languages SET messagecontent = 'Submit', messagekey = 'page.role.submit', locale = 'en' WHERE id = 26;
UPDATE secrets.languages SET messagecontent = 'Aktion', messagekey = 'page.action', locale = 'de' WHERE id = 27;
UPDATE secrets.languages SET messagecontent = 'Action', messagekey = 'page.action', locale = 'en' WHERE id = 28;
UPDATE secrets.languages SET messagecontent = 'Löschen', messagekey = 'page.delete', locale = 'de' WHERE id = 29;
UPDATE secrets.languages SET messagecontent = 'Delete', messagekey = 'page.delete', locale = 'en' WHERE id = 30;
UPDATE secrets.languages SET messagecontent = 'Zurück', messagekey = 'page.back', locale = 'de' WHERE id = 31;
UPDATE secrets.languages SET messagecontent = 'Back', messagekey = 'page.back', locale = 'en' WHERE id = 32;
UPDATE secrets.languages SET messagecontent = 'Übernehmen', messagekey = 'page.profile.submit', locale = 'de' WHERE id = 33;
UPDATE secrets.languages SET messagecontent = 'Submit', messagekey = 'page.profile.submit', locale = 'en' WHERE id = 34;
UPDATE secrets.languages SET messagecontent = 'Angaben zum User...', messagekey = 'page.profile.title', locale = 'de' WHERE id = 35;
UPDATE secrets.languages SET messagecontent = 'Userdata...', messagekey = 'page.profile.title', locale = 'en' WHERE id = 36;
UPDATE secrets.languages SET messagecontent = 'Name:', messagekey = 'page.profile.name', locale = 'de' WHERE id = 37;
UPDATE secrets.languages SET messagecontent = 'Name:', messagekey = 'page.profile.name', locale = 'en' WHERE id = 38;
UPDATE secrets.languages SET messagecontent = 'Usernamen:', messagekey = 'page.profile.username', locale = 'de' WHERE id = 39;
UPDATE secrets.languages SET messagecontent = 'Username:', messagekey = 'page.profile.username', locale = 'en' WHERE id = 40;
UPDATE secrets.languages SET messagecontent = 'E-Mail:', messagekey = 'page.profile.email', locale = 'de' WHERE id = 41;
UPDATE secrets.languages SET messagecontent = 'E-Mail:', messagekey = 'page.profile.email', locale = 'en' WHERE id = 42;
UPDATE secrets.languages SET messagecontent = 'Passwort:', messagekey = 'page.profile.password', locale = 'de' WHERE id = 43;
UPDATE secrets.languages SET messagecontent = 'Password:', messagekey = 'page.profile.password', locale = 'en' WHERE id = 44;
UPDATE secrets.languages SET messagecontent = 'Nr.', messagekey = 'page.admin.nr', locale = 'de' WHERE id = 45;
UPDATE secrets.languages SET messagecontent = 'Nr.', messagekey = 'page.admin.nr', locale = 'en' WHERE id = 46;
UPDATE secrets.languages SET messagecontent = 'Username', messagekey = 'page.admin.username', locale = 'de' WHERE id = 47;
UPDATE secrets.languages SET messagecontent = 'Username', messagekey = 'page.admin.username', locale = 'en' WHERE id = 48;
UPDATE secrets.languages SET messagecontent = 'Name', messagekey = 'page.admin.name', locale = 'de' WHERE id = 49;
UPDATE secrets.languages SET messagecontent = 'Name', messagekey = 'page.admin.name', locale = 'en' WHERE id = 50;
UPDATE secrets.languages SET messagecontent = 'E-Mail', messagekey = 'page.admin.email', locale = 'de' WHERE id = 51;
UPDATE secrets.languages SET messagecontent = 'E-Mail', messagekey = 'page.admin.email', locale = 'en' WHERE id = 52;
UPDATE secrets.languages SET messagecontent = 'Rolle(n)', messagekey = 'page.admin.roles', locale = 'de' WHERE id = 53;
UPDATE secrets.languages SET messagecontent = 'Roles', messagekey = 'page.admin.roles', locale = 'en' WHERE id = 54;
UPDATE secrets.languages SET messagecontent = 'Aktion', messagekey = 'page.admin.action', locale = 'de' WHERE id = 55;
UPDATE secrets.languages SET messagecontent = 'Action', messagekey = 'page.admin.action', locale = 'en' WHERE id = 56;
UPDATE secrets.languages SET messagecontent = 'Löschen', messagekey = 'page.admin.delete', locale = 'de' WHERE id = 57;
UPDATE secrets.languages SET messagecontent = 'Delete', messagekey = 'page.admin.delete', locale = 'en' WHERE id = 58;
UPDATE secrets.languages SET messagecontent = 'Rollen', messagekey = 'page.admin.btn.roles', locale = 'de' WHERE id = 59;
UPDATE secrets.languages SET messagecontent = 'Roles', messagekey = 'page.admin.btn.roles', locale = 'en' WHERE id = 60;
UPDATE secrets.languages SET messagecontent = 'Löschen', messagekey = 'page.admin.btn.delete', locale = 'de' WHERE id = 61;
UPDATE secrets.languages SET messagecontent = 'Delete', messagekey = 'page.admin.btn.delete', locale = 'en' WHERE id = 62;
UPDATE secrets.languages SET messagecontent = 'Sperren', messagekey = 'page.admin.btn.lock', locale = 'de' WHERE id = 63;
UPDATE secrets.languages SET messagecontent = 'Lock', messagekey = 'page.admin.btn.lock', locale = 'en' WHERE id = 64;
UPDATE secrets.languages SET messagecontent = 'Entsperren', messagekey = 'page.admin.btn.unlock', locale = 'de' WHERE id = 65;
UPDATE secrets.languages SET messagecontent = 'Unlock', messagekey = 'page.admin.btn.unlock', locale = 'en' WHERE id = 66;
